version: '3'

services:
    db:
        image: mysql:5.7
        container_name: db_uekles_container
        restart: always
        command: --max_allowed_packet=32505856
        volumes:
            - uekles-db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_uekles_container
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
    server:
        build: apache-php
        container_name: server_uekles_container
        hostname: "uekles.uekles.local.dev"
        ports:
            - "8085:80"
        volumes:
            - ./apache-php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        links:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    uekles-db-data: {}
